--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which season has the highest sales volume?
SELECT season,
       COUNT(*) AS total_sales,
       ROUND(SUM(purchase_amount), 2) AS total_revenue,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
GROUP BY season
ORDER BY total_sales DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Find customers with high purchase amounts but low review ratings
SELECT customer_id,purchase_amount,review_rating,item_purchased,category
FROM customer
WHERE purchase_amount > 70 
  AND review_rating < 3.0
ORDER BY purchase_amount DESC

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue desc,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7 Which are top 10 revenue-generating states ?
SELECT location,
       COUNT(*) AS total_orders,
       ROUND(SUM(purchase_amount), 2) AS total_revenue,
       ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;


--Q8 Payment method usage and revenue
SELECT payment_method,
       COUNT(*) AS transaction_count,
       ROUND(SUM(purchase_amount), 2) AS total_revenue,
       ROUND(AVG(purchase_amount), 2) AS avg_transaction_value
FROM customer
GROUP BY payment_method
ORDER BY transaction_count DESC;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group ?
select * from customer limit 5
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group

order by total_revenue desc

